package com.um.puak

enum class Province {
    Aceh,
    Bali,
    Bangka_Belitung,
    Bengkulu,
    Banten,
    Gorontalo,
    Jambi,
    Jawa_Barat,
    Jawa_Timur,
    Jakarta,
    Jawa_Tengah,
    Kalimantan_Barat,
    Kalimantan_Timur,
    Kepulauan_Riau,
    Kalimantan_Selatan,
    Kalimantan_Tengah,
    Kalimatan_Utara,
    Lampung,
    Maluku,
    Maluku_Utara,
    Nusa_Tenggara_Barat,
    Nusa_Tenggara_Timur,
    Papua,
    Papua_Barat,
    Riau,
    Sulawesi_Utara,
    Sumatera_Barat,
    Sulawesi_Tenggara,
    Sulawesi_Selatan,
    Sulawesi_Barat,
    Sumatera_Selatan,
    Sulawesi_Tengah,
    Sumatera_Utara,
    Yogyakarta
}